# Generated by Django 5.2 on 2025-04-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishitems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishitemmodel",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
