# Generated by Django 5.2 on 2025-04-21 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wishitems", "0003_wishitemmodel_reserved_wishitemmodel_reserved_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishitemmodel",
            options={"ordering": ["title"]},
        ),
    ]
