name: Export environment variables
runs:
  using: "composite"
  steps:
    - run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
        echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
        echo "MINIO_HOST=${{ secrets.MINIO_HOST }}" >> $GITHUB_ENV
        echo "MINIO_PORT=${{ secrets.MINIO_PORT }}" >> $GITHUB_ENV
        echo "MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }}" >> $GITHUB_ENV
        echo "MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}" >> $GITHUB_ENV
        echo "MINIO_SECURE=${{ secrets.MINIO_SECURE }}" >> $GITHUB_ENV
      shell: bash
