# Generated by Django 5.2.1 on 2025-05-21 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_alter_registrationtokenmodel_token"),
        ("wishitems", "0003_alter_wishitemmodel_reserved_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationtokenmodel",
            name="wishitem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wishitems.wishitemmodel",
            ),
        ),
    ]
