# Generated by Django 5.2 on 2025-04-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishitems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishitemmodel",
            name="price",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="wishitemmodel",
            name="price_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("₽", "RUB"),
                    ("$", "USD"),
                    ("€", "EUR"),
                ],
            ),
        ),
    ]
