# Generated by Django 5.2.1 on 2025-05-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishitems", "0002_wishitemmodel_price_wishitemmodel_price_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishitemmodel",
            name="reserved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
